-- HR DB 資料查詢
-- 查詢每個部門高於平均部門薪資的員工
-- (結果依部門平均薪資降冪排序)

-- 1.查詢每個部門的平均薪資
-- 2.查詢高於部門平均薪資的員工

-- 簡單子查詢
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID,
	D.DEPARTMENT_NAME,
	DEP_AVG_SALARY.AVG_SALARY
FROM (
	SELECT DEPARTMENT_ID, FLOOR(AVG(SALARY)) "AVG_SALARY"
	FROM EMPLOYEES
	GROUP BY DEPARTMENT_ID
) DEP_AVG_SALARY
JOIN EMPLOYEES E ON E.DEPARTMENT_ID = DEP_AVG_SALARY.DEPARTMENT_ID
JOIN DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE E.SALARY > DEP_AVG_SALARY.AVG_SALARY
ORDER BY E.DEPARTMENT_ID, E.SALARY DESC;

-- 相關子查詢 WITH AS
WITH DEP_AVG_SALARY AS (
	SELECT DEPARTMENT_ID, FLOOR(AVG(SALARY)) "AVG_SALARY"
	FROM EMPLOYEES
	GROUP BY DEPARTMENT_ID
),
GREATER_DEP_EMP AS (
	SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID, DEP_AVG_SALARY.AVG_SALARY
    FROM EMPLOYEES E
    JOIN DEP_AVG_SALARY ON DEP_AVG_SALARY.DEPARTMENT_ID = E.DEPARTMENT_ID
    WHERE E.SALARY > DEP_AVG_SALARY.AVG_SALARY
)
SELECT GDE.EMPLOYEE_ID, GDE.FIRST_NAME, GDE.SALARY, GDE.DEPARTMENT_ID, D.DEPARTMENT_NAME, GDE.AVG_SALARY
FROM GREATER_DEP_EMP GDE
JOIN DEPARTMENTS D ON D.DEPARTMENT_ID = GDE.DEPARTMENT_ID
ORDER BY GDE.AVG_SALARY DESC, GDE.SALARY DESC;




