 DROP TABLE BOOK_CUSTOMER_ORDER;
 DROP TABLE COFFEE_CUSTOMER_ORDER;
 DROP TABLE MRT_TRANSIT_TRAFFIC;
 DROP TABLE CUSTOMER;
 DROP TABLE AMAZON_INC;
 DROP TABLE STARBUCKS_INC;

-- 顧客資料表
CREATE TABLE CUSTOMER 
(
  CUS_IDENTIFIER_ID VARCHAR(10) PRIMARY KEY -- '顧客身份證字號'
, CUS_NAME VARCHAR(50) -- '顧客姓名'
, CUS_SEX VARCHAR(10) -- '顧客姓別'
, CUS_AGE VARCHAR(10) -- '顧客年齡'
, CUS_PHONE_ENUMBER VARCHAR(20) -- '顧客手機號碼'
, IS_DIFFICULT_CUS VARCHAR(1) -- '奧客(1:是、0:否)'
);


-- 捷運轉運流量
CREATE TABLE MRT_TRANSIT_TRAFFIC
(
	STATION_ID VARCHAR(10) -- '車站編號'
	,STATION_NAME VARCHAR(50) -- '車站名稱'
	,STATION_LINE VARCHAR(50) -- '車站路線'
	,STATION_DEPARTURE_TIME datetime -- '發車時間'
	,TRAFFIC_PEOPLE_QUANTITY NUMERIC(10,0) -- '轉運人數流量'
	, CONSTRAINT MRT_TRANSIT_TRAFFIC_PK PRIMARY KEY (STATION_ID, STATION_DEPARTURE_TIME)
);



-- 星巴客公司
CREATE TABLE STARBUCKS_INC
(
	 STORE_ID VARCHAR(20) PRIMARY KEY -- '門市編號'
	,STORE_NAME VARCHAR(100) -- '門市名稱'
	,STORE_ADDR VARCHAR(100) -- '門市地址'
	,STORE_TYPE VARCHAR(100) -- '門市捷運站點'
	,STORE_MRT VARCHAR(100) -- '門市型態'
);



-- 阿馬龍公司
CREATE TABLE AMAZON_INC
(
	 STORE_ID VARCHAR(20) PRIMARY KEY -- '書店編號'
	,STORE_NAME VARCHAR(100) -- '書店名稱'
	,STORE_ADDR VARCHAR(100) -- '書店名稱'
	,STORE_BOOK_SALE_TYPE VARCHAR(100) -- '書店捷運站點'
	,STORE_MRT VARCHAR(100) -- '販售書籍類型'
);


-- 咖啡顧額訂單
CREATE TABLE COFFEE_CUSTOMER_ORDER
(
	 ORDER_NO VARCHAR(20) PRIMARY KEY -- '訂單編號'
	,ORDER_DATE datetime -- '購買日期'
	,ORDER_AMOUNT NUMERIC(10,0) -- '購買金額'
	,BUY_GOODS_TYPE VARCHAR(20) -- '購買商品種類'
	,CUS_IDENTIFIER_ID VARCHAR(10) REFERENCES CUSTOMER(CUS_IDENTIFIER_ID) -- '顧客身份證字號'
	,COFFEE_STORE_ID VARCHAR(20) REFERENCES STARBUCKS_INC(STORE_ID) -- '門市編號'
);



-- 書籍顧額訂單
CREATE TABLE BOOK_CUSTOMER_ORDER
(
	 ORDER_NO VARCHAR(20) PRIMARY KEY -- '訂單編號'
	,ORDER_DATE datetime -- '購買日期'
	,ORDER_AMOUNT NUMERIC(10,0) -- '購買金額'
	,BUY_BOOK_TYPE VARCHAR(20) -- '購買書籍種類'
	,CUS_IDENTIFIER_ID VARCHAR(10) REFERENCES CUSTOMER(CUS_IDENTIFIER_ID) -- '顧客身份證字號'
	,BOOK_STORE_ID VARCHAR(20) REFERENCES AMAZON_INC(STORE_ID) -- '書店編號'
);

